
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: ${CLEARDB_DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver: org.h2.Driver
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    platform: mysql

server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false
    path: /error

fish:
  orders:
    pageSize: 5